---
- name: Wait 300 seconds for port 22 to become open and contain "OpenSSH"
  hosts: all
  gather_facts: False
  tasks:
    - ansible.builtin.wait_for:
        port: 22
        delay: 10
        timeout: 100
        search_regex: OpenSSH
        host: '{{ (ansible_ssh_host|default(ansible_host))|default(inventory_hostname) }}'
      vars:
        ansible_connection: local

- name: Deploy Docker
  hosts: all
  become: true
  tasks:
    - name: Install Docker 
      ansible.builtin.yum:
        update_cache: true
        name: docker
        state: present

    - name: Install Docker-compose 
      ansible.builtin.get_url:
        url: https://github.com/docker/compose/releases/latest/download/docker-compose-Linux-x86_64
        dest: /usr/local/bin/docker-compose
        mode: "0755"

    - name: Start Docker daemon
      ansible.builtin.systemd:
        name: docker
        state: started 

    - name: Add ec2-user to docker group
      ansible.builtin.user:
        name: ec2-user
        groups: docker
        append: true
        
    - name: Reset ssh connection to allow user changes to affect 'current login user'
      ansible.builtin.meta: reset_connection
    - name: Install Docker Python module   
      ansible.builtin.pip:
         name: 
           - docker
           - docker-compose

- name: Start Docker containers
  hosts: all
  vars_files:
    - variable.yaml
  tasks:
    - name: Docker login
      community.docker.docker_login:
        registry_url: https://index.docker.io/v1/
        username: "{{docker_id}}"
        password: "{{docker_password}}"

    - name: Copy Docker compose file
      ansible.builtin.copy:
        src: /Users/zqwang/bootcamp-projects/ansible/docker-compose.yaml
        dest: /home/ec2-user/docker-compose.yaml
    - name: Excute docker-compose.yaml file
      community.docker.docker_compose:
        project_src: /home/ec2-user/
        state: present