---
- name: Wait 300 seconds for port 22 to become open and contain "OpenSSH"
  hosts: all
  gather_facts: False
  tasks:
    - ansible.builtin.wait_for:
        port: 22
        delay: 10
        timeout: 100
        search_regex: OpenSSH
        host: '{{ (ansible_ssh_host|default(ansible_host))|default(inventory_hostname) }}'
      vars:
        ansible_connection: local

- name: Deploy Docker
  hosts: all
  become: true
  roles:
    - deploy_docker

- name: Start Docker containers
  hosts: all
  vars_files:
    - variable.yaml
  roles:
    - start_containers