---
- name: Update kubeconfig file
  hosts: localhost
  tasks:
    - name: Update kubeconfig file
      ansible.builtin.command: aws eks update-kubeconfig --name myapp-eks-cluster 

- name: Deploy app in a new namespace
  hosts: localhost
  tasks:
    - name: Create a k8s namespace
      kubernetes.core.k8s:
        name: my-app
        api_version: v1
        kind: Namespace
        state: present
    - name: Deploy Nginx app
      kubernetes.core.k8s:
        src: /Users/zqwang/nginx.yaml
        state: present
        namespace: my-app